bias: true
block_size: 4096
gelu_approximate: none
head_size: 128
hf_config:
  name: stablelm-base-alpha-3b
  org: stabilityai
intermediate_size: 16384
lm_head_bias: false
mlp_class_name: GptNeoxMLP
n_embd: 4096
n_expert: 0
n_expert_per_token: 0
n_head: 32
n_layer: 16
n_query_groups: 32
name: stablelm-base-alpha-3b
norm_class_name: LayerNorm
norm_eps: 1.0e-05
padded_vocab_size: 50688
padding_multiple: 512
parallel_residual: true
rope_base: 10000
rope_condense_ratio: 1
rotary_percentage: 0.25
scale_embeddings: false
shared_attention_norm: false
vocab_size: 50254
embed_choices:  [512, 1024, 2048, 4096]
head_choices: [8, 16, 32]
layer_choices: [14, 15, 16]
mlp_ratio_choices: [2, 3, 4]
bias_choices: [True, False]
_mlp_class: "GptNeoxMLP"
_norm_class: "LayerNorm"